/u/ssoma1/.local/lib/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
Traceback (most recent call last):
  File "/u/ssoma1/mahdi/Isomorphic-Pruning/prune.py", line 296, in <module>
    main()
  File "/u/ssoma1/mahdi/Isomorphic-Pruning/prune.py", line 136, in main
    base_macs, base_params = tp.utils.count_ops_and_params(model, example_inputs)
  File "/u/ssoma1/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/u/ssoma1/.local/lib/python3.9/site-packages/torch_pruning/utils/op_counter.py", line 35, in count_ops_and_params
    _ = flops_model(example_inputs)
  File "/u/ssoma1/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/ssoma1/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/ssoma1/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
  File "/u/ssoma1/.local/lib/python3.9/site-packages/timm/models/vision_transformer.py", line 993, in forward
    x = self.forward_features(x, attn_mask=attn_mask)
  File "/u/ssoma1/.local/lib/python3.9/site-packages/timm/models/vision_transformer.py", line 948, in forward_features
    x = self.blocks(x)
  File "/u/ssoma1/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/ssoma1/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/u/ssoma1/.local/lib/python3.9/site-packages/torch/nn/modules/container.py", line 240, in forward
    input = module(input)
  File "/u/ssoma1/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/ssoma1/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
    return forward_call(*args, **kwargs)
  File "/u/ssoma1/.local/lib/python3.9/site-packages/timm/models/vision_transformer.py", line 176, in forward
    x = x + self.drop_path1(self.ls1(self.attn(self.norm1(x), attn_mask=attn_mask)))
  File "/u/ssoma1/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/ssoma1/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
    return inner()
  File "/u/ssoma1/.local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1805, in inner
    result = forward_call(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'attn_mask'
